### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by ylluminate** [uxnow/flappylearning-v#1]
Great work on this awesome little ML exercise! Please pop onto the Discord chat when you have a chance:
https://discord.gg/vlang

Specifically, there's been some discussion in #showcase-discussion and it's been shared in the #showcase:
https://discordapp.com/channels/592103645835821068/592118040179507207/791298438209339393

**Comment by uxnow** [comment]
thanks, I will be there. ’vlang is amazing!

**Comment by medvednikov** [comment]
Hi @uxnow 

What a great little program! It also works nicely with -autofree.

Would you be ok with licensing it under MIT and having this added to V's official examples, with your copyrights?

This will also mean that it will be tested by CI and will be always running correctly.

**Comment by uxnow** [comment]
ok, thank you!
